[build]
builder = "dockerfile"

[deploy]
startCommand = "python deploy/railway_web.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app"
DEPLOYMENT_MODE = "web"
# CANNY_API_KEY = "set-via-railway-dashboard"  # Optional: For Canny feedback analysis
# CANNY_BASE_URL = "https://canny.io/api/v1"

[environments.cron]
[environments.cron.variables]
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app"
DEPLOYMENT_MODE = "cron"
ANALYSIS_TYPE = "weekly"

# Railway service configuration
[service]
name = "intercom-analysis-tool"
description = "Intercom Analysis Tool with Chat Interface"
