"""
EditorAgent: Quality control agent for refining insights before formatting.

This agent implements the "Critic/Editor" pattern from LangChain/LangGraph research.
Its sole responsibility is to read the raw insights generated by InsightAgent
and rewrite them to be more specific, distinct, and actionable.

Key Responsibilities:
1. Detect and fix repetitive phrases ("Customers are experiencing severe frustration...")
2. Sharpen vague insights (replace "Product Question issues" with "API slide generation overflow")
3. Ensure distinctness between topics (Billing != Account)
4. Verify "So What?" factor (business impact)
"""

import logging
import json
from typing import Dict, Any, List, Optional, Tuple
from datetime import datetime

from src.agents.base_agent import BaseAgent, AgentResult, AgentContext, ConfidenceLevel
from src.utils.ai_client_helper import get_ai_client

logger = logging.getLogger(__name__)


class EditorAgent(BaseAgent):
    """Agent specialized in critiquing and rewriting insights for quality."""
    
    def __init__(self):
        super().__init__(
            name="EditorAgent",
            temperature=0.4  # Lower temperature for focused editing
        )
        self.ai_client = get_ai_client()
        self.scoring_temperature = 0.2
    
    def get_agent_specific_instructions(self) -> str:
        """Editor agent specific instructions"""
        return """
YOU ARE THE EDITOR-IN-CHIEF.
Your job is to take a draft analysis and rewrite it to be sharp, distinct, and non-repetitive.

CRITICAL QUALITY RULES:
1. **No Repetition:** If multiple topics say "Customers are experiencing severe frustration", rewrite them. Use varied, specific emotional descriptors (e.g., "Anxiety about overcharges" vs. "Annoyance with login loops").
2. **Specificity is King:** Never say "Product Questions are rising." Say "Questions about API-generated slides are rising."
3. **Distinctness:** Ensure "Billing" insights (unexpected charges) sound different from "Account" insights (login issues).
4. **Active Voice:** Change "It was observed that..." to "We observed..." or direct statements.
5. **No Fluff:** Remove generic padding like "It is important to note that..."

INPUT DATA:
You will receive a JSON object containing 'executive_summary', 'major_themes', and topic-specific 'insights'.

YOUR TASK:
Rewrite the content to meet the quality rules. Return the improved JSON structure.
Do NOT change the data values (numbers, counts), only the narrative text.
"""
    
    def get_task_description(self, context: AgentContext) -> str:
        """Describe the editing task"""
        return "Review and rewrite the analysis insights to eliminate repetition and improve specificity."
    
    def _build_editor_payload(self, context: AgentContext) -> Dict[str, Any]:
        """Build structured payload for scoring/rewrite"""
        # We need the InsightAgent results and potentially Topic summaries
        if not context.previous_results:
            return {
                'executive_summary': '',
                'major_themes': [],
                'recommendations': [],
                'topic_insights': {}
            }
            
        insight_data = context.previous_results.get('InsightAgent', {}).get('data', {})
        topic_sentiments = context.previous_results.get('TopicSentiments', {})
        
        # Simplify the input for the LLM
        editor_input: Dict[str, Any] = {
            'executive_summary': insight_data.get('executive_summary', ''),
            'major_themes': insight_data.get('major_themes', []),
            'recommendations': insight_data.get('recommendations', []),
            'topic_insights': {}
        }
        
        # Extract topic specific insights if available
        if topic_sentiments:
            for topic, data in topic_sentiments.items():
                # Handle nested data structures
                val = data.get('data', data) if isinstance(data, dict) else data
                insight = val.get('sentiment_insight') or val.get('sentiment')
                if insight:
                    editor_input['topic_insights'][topic] = insight
                    
        return editor_input

    def format_context_data(self, context: AgentContext) -> str:
        """Format data for the editor"""
        editor_input = self._build_editor_payload(context)
        return json.dumps(editor_input, indent=2, default=str)

    def validate_input(self, context: AgentContext) -> bool:
        """Validate input availability"""
        if not context.previous_results:
            raise ValueError("No previous results to edit")
        if 'InsightAgent' not in context.previous_results:
            # We can technically edit without InsightAgent if we have TopicSentiments, 
            # but it's better to have both. For now, soft warning.
            logger.warning("InsightAgent results missing for EditorAgent")
        return True

    def validate_output(self, result: Dict[str, Any]) -> bool:
        """Validate editor output structure"""
        # We expect the same structure as input but refined
        return True

    def _map_metric_density(self, metric_count: int) -> float:
        if metric_count >= 8:
            return 1.0
        if metric_count >= 5:
            return 0.7
        if metric_count >= 2:
            return 0.4
        return 0.0

    def _map_repetition_score(self, duplicate_ratio: float) -> float:
        if duplicate_ratio <= 0.10:
            return 1.0
        if duplicate_ratio <= 0.15:
            return 0.7
        if duplicate_ratio <= 0.30:
            return 0.4
        return 0.0

    def _clamp_score(self, value: Optional[float]) -> float:
        try:
            return max(0.0, min(1.0, float(value)))
        except (TypeError, ValueError):
            return 0.5

    def _calculate_composite(
        self,
        specificity: float,
        metric_density: float,
        repetition: float,
        distinctness: float,
        actionability: float
    ) -> float:
        return (
            (specificity * 0.25)
            + (metric_density * 0.25)
            + (repetition * 0.25)
            + (distinctness * 0.15)
            + (actionability * 0.10)
        )

    def _build_default_scores(
        self,
        metric_count: int,
        duplicate_ratio: float,
        issues: Optional[List[str]] = None,
        guidance: str = ""
    ) -> Dict[str, Any]:
        metric_density = self._map_metric_density(metric_count)
        repetition = self._map_repetition_score(duplicate_ratio)
        default_score = 0.5
        composite = self._calculate_composite(
            default_score,
            metric_density,
            repetition,
            default_score,
            default_score
        )
        rewrite_needed = (
            composite < 0.60
            or default_score < 0.6
            or metric_density < 0.5
            or repetition < 0.7
        )
        return {
            'specificity_score': default_score,
            'metric_density_score': metric_density,
            'repetition_score': repetition,
            'distinctness_score': default_score,
            'actionability_score': default_score,
            'composite_score': composite,
            'rewrite_needed': rewrite_needed,
            'issues_found': issues or ["Unable to compute critic scores"],
            'rewrite_guidance': guidance or "Review insights manually for specificity and repetition issues."
        }

    async def _score_insights(
        self,
        context: AgentContext,
        editor_payload: Dict[str, Any]
    ) -> Tuple[Dict[str, Any], int]:
        insight_data = context.previous_results.get('InsightAgent', {}).get('data', {})
        duplicate_ratio = float(insight_data.get('insight_duplicate_ratio') or 0.0)
        metric_count = int(insight_data.get('metric_references_count') or 0)

        critic_prompt = f"""
You are a Quality Critic evaluating Voice of Customer insights.

Assess the following report across three dimensions (0.0-1.0 scale):
1. Specificity - Are insights concrete vs. generic?
2. Distinctness - Do topics sound unique?
3. Actionability - Are next steps clear and specific?

Return JSON with the fields: specificity_score, distinctness_score, actionability_score,
rewrite_needed (true/false), issues_found (list of strings), rewrite_guidance (string).

REPORT PAYLOAD:
{json.dumps(editor_payload, indent=2, default=str)}
"""
        messages = [
            {"role": "system", "content": "You are a strict quality critic for customer experience reports."},
            {"role": "user", "content": critic_prompt}
        ]

        score_tokens = 0
        try:
            response = await self.ai_client.chat.completions.create(
                model=self.model,
                messages=messages,
                temperature=self.scoring_temperature,
                response_format={"type": "json_object"}
            )
            score_tokens = response.usage.total_tokens if response.usage else 0
            payload = json.loads(response.choices[0].message.content)
        except Exception as exc:
            logger.warning("EditorAgent critic scoring failed: %s", exc)
            return self._build_default_scores(metric_count, duplicate_ratio), score_tokens

        specificity = self._clamp_score(payload.get('specificity_score'))
        distinctness = self._clamp_score(payload.get('distinctness_score'))
        actionability = self._clamp_score(payload.get('actionability_score'))
        metric_density = self._map_metric_density(metric_count)
        repetition = self._map_repetition_score(duplicate_ratio)
        composite = self._calculate_composite(
            specificity,
            metric_density,
            repetition,
            distinctness,
            actionability
        )

        rewrite_needed = (
            bool(payload.get('rewrite_needed'))
            or composite < 0.60
            or specificity < 0.6
            or metric_density < 0.5
            or repetition < 0.7
        )

        issues = payload.get('issues_found', [])
        if isinstance(issues, str):
            issues = [issues]
        elif not isinstance(issues, list):
            issues = list(issues) if issues else []

        critic_scores = {
            'specificity_score': specificity,
            'metric_density_score': metric_density,
            'repetition_score': repetition,
            'distinctness_score': distinctness,
            'actionability_score': actionability,
            'composite_score': composite,
            'rewrite_needed': rewrite_needed,
            'issues_found': issues,
            'rewrite_guidance': payload.get('rewrite_guidance', '').strip()
        }
        return critic_scores, score_tokens

    async def _rewrite_insights(
        self,
        editor_payload: Dict[str, Any],
        critic_scores: Dict[str, Any]
    ) -> Tuple[Optional[Dict[str, Any]], int]:
        issues = critic_scores.get('issues_found') or []
        guidance = critic_scores.get('rewrite_guidance') or ""
        rewrite_prompt = f"""
You are the Editor-in-Chief. Improve the following insights per the critic feedback.

Critic Issues:
{json.dumps(issues, indent=2)}

Rewrite Guidance:
{guidance}

Rewrite the report to be specific, distinct, and actionable. Keep JSON structure with keys:
executive_summary, major_themes, recommendations, topic_insights.

CURRENT REPORT:
{json.dumps(editor_payload, indent=2, default=str)}
"""
        messages = [
            {"role": "system", "content": self.get_agent_specific_instructions()},
            {"role": "user", "content": rewrite_prompt}
        ]

        rewrite_tokens = 0
        try:
            response = await self.ai_client.chat.completions.create(
                model=self.model,
                messages=messages,
                temperature=self.temperature,
                response_format={"type": "json_object"}
            )
            rewrite_tokens = response.usage.total_tokens if response.usage else 0
            refined_data = json.loads(response.choices[0].message.content)
            return refined_data, rewrite_tokens
        except Exception as exc:
            logger.error("EditorAgent rewrite failed: %s", exc)
            return None, rewrite_tokens

    def _determine_confidence_level(self, composite_score: float) -> ConfidenceLevel:
        if composite_score >= 0.75:
            return ConfidenceLevel.HIGH
        if composite_score >= 0.60:
            return ConfidenceLevel.MEDIUM
        return ConfidenceLevel.LOW

    async def execute(self, context: AgentContext) -> AgentResult:
        """Execute critic scoring followed by optional rewrite."""
        start_time = datetime.now()
        score_tokens = 0
        rewrite_tokens = 0
        
        try:
            self.validate_input(context)
            editor_payload = self._build_editor_payload(context)
            
            critic_scores, score_tokens = await self._score_insights(context, editor_payload)
            logger.info(
                "EditorAgent critic scores | composite=%.2f specificity=%.2f metric_density=%.2f repetition=%.2f",
                critic_scores.get('composite_score', 0.0),
                critic_scores.get('specificity_score', 0.0),
                critic_scores.get('metric_density_score', 0.0),
                critic_scores.get('repetition_score', 0.0)
            )
            logger.info("EditorAgent scoring tokens used: %s", score_tokens)
            
            rewrite_performed = False
            refined_output: Optional[Dict[str, Any]] = None
            if critic_scores.get('rewrite_needed'):
                refined_output, rewrite_tokens = await self._rewrite_insights(editor_payload, critic_scores)
                rewrite_performed = refined_output is not None
                logger.info("EditorAgent rewrite tokens used: %s", rewrite_tokens)
                if rewrite_performed:
                    logger.info("✍️ EditorAgent performed rewrite based on critic feedback")
                else:
                    logger.warning("EditorAgent rewrite requested but failed; using original insights")
            
            final_insights = refined_output or editor_payload
            result_data = {
                'critic_scores': critic_scores,
                'revised_insights': final_insights,
                'rewrite_performed': rewrite_performed
            }
            
            execution_time = (datetime.now() - start_time).total_seconds()
            composite_score = critic_scores.get('composite_score', 0.0)
            confidence_level = self._determine_confidence_level(composite_score)
            
            return AgentResult(
                agent_name=self.name,
                success=True,
                data=result_data,
                confidence=composite_score,
                confidence_level=confidence_level,
                sources=["InsightAgent", "EditorAgent"],
                execution_time=execution_time,
                token_count=score_tokens + rewrite_tokens
            )
            
        except Exception as e:
            logger.error("EditorAgent failed: %s", e, exc_info=True)
            return AgentResult(
                agent_name=self.name,
                success=False,
                data={},
                confidence=0.0,
                confidence_level=ConfidenceLevel.LOW,
                error_message=str(e),
                execution_time=(datetime.now() - start_time).total_seconds()
            )

